# Generated by Django 3.2.6 on 2021-10-20 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('status', models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], max_length=15)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=60)),
                ('keywords', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('price', models.FloatField(blank=True, null=True)),
                ('sizes', models.CharField(blank=True, max_length=10, null=True)),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('available', models.CharField(blank=True, choices=[('In Stock', 'In Stock'), ('Out of Stock', 'Out of Stock'), ('Restocked', 'Restocked')], max_length=30, null=True)),
                ('quantity_instock', models.IntegerField(blank=True, null=True)),
                ('minquantity', models.IntegerField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True)),
                ('status', models.CharField(blank=True, choices=[('True', 'True'), ('True', 'True')], max_length=30)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('featured', models.BooleanField(blank=True)),
                ('latest', models.BooleanField(blank=True)),
                ('banner', models.BooleanField(blank=True)),
                ('offer', models.BooleanField(blank=True)),
                ('detail', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
        ),
    ]
