# Generated by Django 3.2.6 on 2021-10-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('brands', models.ImageField(blank=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('keywords', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255, null=True)),
                ('company', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('secondary_phone', models.CharField(max_length=15, null=True)),
                ('fax', models.CharField(blank=True, max_length=15)),
                ('secondary_fax', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('secondary_email', models.CharField(blank=True, max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images')),
                ('cart_img', models.ImageField(blank=True, null=True, upload_to='images')),
                ('About_img_1', models.ImageField(blank=True, null=True, upload_to='images')),
                ('About_img_2', models.ImageField(blank=True, null=True, upload_to='images')),
                ('facebook', models.CharField(blank=True, max_length=50)),
                ('instagram', models.CharField(blank=True, max_length=50)),
                ('twitter', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('about', models.TextField(blank=True)),
                ('contact', models.TextField(blank=True)),
            ],
        ),
    ]
