# Generated by Django 3.2.6 on 2022-02-18 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20211124_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='cart_img',
            new_name='favicon',
        ),
    ]
